### PR TITLE
ability to specify placement group

### PR DESCRIPTION
**Pull request by andersonbd1**

### CODE REVIEW

**Comment by terrancesnyder** [comment]
+1

**Comment by yoramshai** [comment]
+1

**Comment by davidski** [comment]
Is this request going to be evaluated and merged anytime soon? It's been outstanding a _long_ time. :disappointed:

**Comment by manjunath1992** [comment]
+1

**Comment by poflynn** [comment]
+1

**Comment by VVMichaelSawyer** [comment]
+1

**Pull request closed without merging**
